apiVersion: v1
kind: Service
metadata:
  name: book-app-lb
  namespace: default
  labels:
    app: book-app
spec:
  type: LoadBalancer
  selector:
    app: book-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80